spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/health-shop
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

  datasource:
    url: jdbc:mysql://localhost:3306/health_shop?useSSL=false&allowPublicKeyRetrieval=true
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
    defer-datasource-initialization: true  # hibernate 초기화 이후 data.sql이 실행되도록 변경
  sql:
    init:
      mode: always # 추가

logging:
  level:
    org:
      hibernate.SQL: debug
#      springframework.security: debug  # 임시로 추가